### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by munkm** [data-exp-lab/widgyts#37]
We have some basic documentation for this repository, but it needs to be improved. This should include: 
- [ ] adding extra example notebooks (see also data-exp-lab/wigyts#33 and data-exp-lab/wigyts#36) that show more broadly the uses of widgyts
- [ ] a clearly stated list of dependencies for installation (we need to specify how widgyts functionality differs if yt is loaded and not loaded or installed/not installed) 
- [ ] contribution guidelines (maybe also issue and PR templates)
- [ ] make it clear who our users are! 
- [ ] guidelines for how to seek help for widgyts (maybe linking to the yt slack? we could make a widgyts channel?) Do we also want to create a mailing list for help?

**Comment by MatthewTurk** [comment]
I don't think a specific ML is necessary for this project.  I do think having extra notebooks would be great, and the dependencies are a definite.

API docs too, probably.

**Comment by munkm** [comment]
Once the API docs render properly this issue can be closed.

**Comment by matthewturk** [comment]
They render now!
